### ISSUE TITLE
Different embedding models

### ISSUE THREAD

**Issue by erickrf** [nlx-group/lx-dsemvectors#2]
What are the differences among the embedding models available at http://lxcenter.di.fc.ul.pt/datasets/models/? Could you add some information about it in the readme or somewhere?

**Comment by nlx-group** [comment]
The differences among the embeddings are explained in the [article](http://www.di.fc.ul.pt/~ahb/pubs/2016RodriguesBrancoNealeSilva.pdf) referred in the Readme (each model corresponds to a different set of parameters, for more details see table 7 from the article).
