### ISSUE TITLE
Analogies as identities

### ISSUE THREAD

**Issue by wal-iston** [nlx-group/lx-dsemvectors#3]
Hi, I found some analogies that are rahter identities, such as:
(alegre, alegremente, alegre, alegremente) in gram1-adjective-to-adverb
(agradável, desagradável, agradável, desagradável) in gram2-opposite

Can you give me a hint for why are these in the testset for analogy?

**Comment by joaoantonioverdade** [comment]
These shouldn't be in the data.
I counted 27 occurrences in the analogies (0.15% from the total 17487).
Thank you for letting us know, we will update a new version.

It follows the reason for future reference.
The algorithm for the combination of pairs is based on the reference pairs (English), when generating the corpus for Portuguese it did not take into account possible identical translations.

Word pairs such as:
cheerful	translated to alegre
cheerfully translated to	alegremente
were paired with other pairs with the same translation:
happy	translated to alegre
happily	translated to alegremente
